# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='name1', max_length=50)),
                ('column_name', models.CharField(default='ColumnName', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('datatype', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='First name')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Surname',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=60, verbose_name='Surname')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.DataType'),
        ),
    ]
