# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='columnName',
            new_name='column_name',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='dataType',
            new_name='data_type',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='rowsNumber',
            new_name='rows_number',
        ),
    ]
