# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='datatype_id',
            new_name='datatype',
        ),
        migrations.RenameField(
            model_name='column',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='datatype',
            old_name='category_id',
            new_name='category',
        ),
    ]
