# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20160415_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='column_name',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='country',
            field=models.TextField(default='All'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='data_type',
            field=models.TextField(default='names'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.TextField(default='name1'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='rows_number',
            field=models.IntegerField(default=1),
        ),
    ]
