# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20160429_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_name', models.CharField(max_length=200)),
                ('relationship_type', models.CharField(choices=[('O2O', 'One to One'), ('O2M', 'One to Many'), ('M2O', 'Many to One'), ('M2M', 'Many to Many')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables_connected', to='generator.Project'),
        ),
        migrations.AddField(
            model_name='table',
            name='relationship',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.Relationship'),
        ),
    ]
