# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20160422_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='options',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
