# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20160415_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='All')),
            ],
        ),
        migrations.AlterField(
            model_name='dataset',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Country'),
        ),
    ]
