# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20160713_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='project',
        ),
        migrations.RemoveField(
            model_name='table',
            name='relationship',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
