# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20160425_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='column_name',
            field=models.CharField(default='ID', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='datatype',
            field=models.CharField(default='Auto-increment', max_length=50),
        ),
    ]
