# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20160418_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datatype', models.CharField(max_length=50, primary_key=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='First name')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Surname',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=60, verbose_name='Surname')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='country',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='rows_number',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='column_name',
            field=models.CharField(default='ColumnName', max_length=200),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='data_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.DataType'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(default='name1', max_length=50),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
