# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20160715_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='options',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
