# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20160425_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, default='TableName', max_length=50, null=True),
        ),
    ]
