# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_auto_20160419_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='id',
        ),
        migrations.AlterField(
            model_name='datatype',
            name='datatype',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
